### PR TITLE
adjusting semver

### PR DESCRIPTION
**Pull request by sbussetti**

### CODE REVIEW

**Comment by ghost** [comment]
I also get blocked from using this loader because of the peer dependency requirement.

@sbussetti I think `>=0.25.0 <0.30.0` is not appropriate. There's no guarantee that 0.29 - 0.30 will be compatible with this plugin (given that 0.28 is current latest version). Unless you know the development plans of `css-loader`.

@smithad15 I think you can just use `>=0.25.0` if you would not like to keep updating whenever a new version of `css-loader` is released, although there's no guarantee that the loader will always work with the latest version of `css-loader`. But since this loader is quite simple, it's much less likely that it no longer works than a new version of `css-loader` is released.

**Comment by sbussetti** [comment]
I'm going by the general guideline that developers should not introduce
breaking changes in minor version upgrades. So if smithad also follows that
generally agreed upon pragma, then yes in a way i do know his development
plans, which is why I limited the top end to be below .30

-- 
Steve Bussetti

From: Martin Chen <notifications@github.com> <notifications@github.com>
Reply: smithad15/css-to-string-loader
<reply@reply.github.com>
<reply@reply.github.com>
Date: April 19, 2017 at 3:26:04 AM
To: smithad15/css-to-string-loader <css-to-string-loader@noreply.github.com>
<css-to-string-loader@noreply.github.com>
CC: Steve Bussetti <steve.bussetti@gmail.com> <steve.bussetti@gmail.com>,
Mention <mention@noreply.github.com> <mention@noreply.github.com>
Subject:  Re: [smithad15/css-to-string-loader] adjusting semver (#6)

I also get blocked from using this loader because of the peer dependency

**Comment by ghost** [comment]
That's only true after major version 1.

> Major version zero (0.y.z) is for initial development. Anything may change at any time. The public API should not be considered stable.

quoted from http://semver.org/

**Comment by ghost** [comment]
And that's why [Caret Ranges](https://github.com/npm/node-semver#caret-ranges-123-025-004) are defined as:

> Allows changes that do not modify the left-most non-zero digit in the [major, minor, patch] tuple.

**Comment by smithad15** [comment]
Thanks for this. As I've had to deal with some peerDependency version issues before, and since semver works a bit differently when dealing with `0.x.x` packages, @sbussetti could you please update the PR to an even more permissive range of `>=0.25.0 <1.0.0` and remove the package version bump as I will do that during my release cycle? I have a fairly high confidence that the `toString` method of `css-loader` won't be changing significantly any time soon and if it does, I will deal with any upstream API changes at that time.

For more semver references, check out https://docs.npmjs.com/misc/semver#caret-ranges-123-025-004 for some more details of how the caret operator changes once you are <1.0.0, if either of you are interested.

**Comment by ghost** [comment]
@sbussetti Are you able to change according to smithad15's suggestion recently?

**Comment by sbussetti** [comment]
@mchencb @smithad15 done and done.  Also @mchencb thanks for the semver clarification.  I was not aware of the exception for 0.x.x !

**Comment by smithad15** [comment]
@sbussetti Thank you for this. Apologies for the delay but I'll push out `0.1.3` shortly.

**Comment by sbussetti** [comment]
No sweat 👌

**Pull request merged**
